import bcrypt from 'bcryptjs';
const data = {
  
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Aio Pc Hp 205 G4 Amd Athlon Silver 3050 4gb ',
      slug: '1',
      category: 'Computer desktop',
      image: '/images/p1.png',
      isFeatured: true,
      featuredImage: '/images/banner1.png',
      price: 370,
      brand: 'HP',
      countInStock: 20,
      description: 'All-in-One HP 205 G4, equipado con nuestra nueva y elegante pantalla con microborde en tres lados, ocupa menos espacio en tu escritorio. Está diseñado para que empieces a usarlo de inmediato: sácalo de la caja, colócalo donde quieras, conéctalo y empieza a trabajar. ',
         
    },
    {
      name: ' AMD Ryzen 9 Titan G',
      slug: '2',
      category: 'Computer gamer',
      image: '/images/p2.png',
      price: 550,
      brand: 'AMD',
      countInStock: 20,
      description: 'Gabinete Gamer Pc Atx Gadnic Apocalipsis Procesador AMD Ryzen 9 c/ video Motherboard Gigabyte A520M-S2H Memoria para PC Crucial 8GB 2666 MHz DDR4 Disco Estado Solido Gigabyte 480GB Fuente Corsair 600w 80 Plus White Teclado Gadnic Retroiluminado Gaming 7 Mouse Gaming Gadnic M3 SHOOT',
    },
    {
      name: 'Gamer AMD FX-6100',
      slug: '3',
      category: 'Computer gamer',
      image: '/images/p3.png',
      isFeatured: true,
      featuredImage: '/images/banner3.png',
      price: 500,     
      brand: 'AMD',
      countInStock: 20,
      description: 'AMD FX-6100 6 NUCLEOS (2 CPU + 4 GPU) CON COOLER BOX VIDEO: RADEON R5 2GB (ONBOARD) Mother: a320m usb 3.0 - sata3 Disco Rigido: 1 TB sata Memoria RAM: 8gb 2666mhz DDR4 Gabinete BRB: fuente 550  Kit: teclado usb, mouse usb y parlantes potenciados,      Sistema operativo: windows 10 64bits (trial)',
    

    },
    {
      name: 'Gamer Intel Core I9 -32gb Ddr4-Ssd 960gb',
      slug: '4',
      category: 'Computer gamer',
      image: '/images/p4.png',
      isFeatured: true,
      featuredImage: '/images/banner2.png',
      price: 690,
      brand: 'Intel',
      description: 'Procesador: INTEL Core I9 10900F Motherboard: SK 1200 H410 Memoria: DDR4 32GB  Almacenamiento: SSD 960Gb Gabinete: GABINETE AEROCOOL SPLIT BLACK GPU: * Necesita una placa de video dedicada para funcionar * Fuente: 500W ATX',
     
    },
    {
      name: 'Gamer Gadnic Destroyer Rgb Atx Lateral Acrilico 6 Coolers',
      slug: '5',
      category: 'Gabinet',
      image: '/images/p6.png',
      isFeatured: true,
      featuredImage: '/images/banner5.png',
      price: 75,
      brand: 'Gadnic',
      countInStock: 20,
      description: 'Material del Gabinete: Revestimiento negro SPCC (acero laminado) de 0,5 mm Compatible con placa base: ATX / M-ATX / ITX    Conectores Frontales: 2 - USB 2.0 + HD AUDIO + 1 - USB3.0 Soporte para Discos 2 - soporta VGA de hasta 300 mm MAX   Soporta CPU de altura 155 mm MAXA ',
     
    },
    {
      name: 'Notebook Lenovo V15 IIL Intel Core I7 10ma Gen 4gb 1tb',
      slug: '6',
      category: 'Notebook',
      image: '/images/p5.png',
      price: 500,
      brand: 'Lenovo',
      countInStock: 20,
      description: 'Lenovo V15 IIL FREE D.O.S: Sin sistema operativo Procesador Intel Core i7-1065G7 (4C / 8T, 1.3 / 3.9GHz, 8MB) Gráficos integrados Intel UHD Chipset Plataforma Intel SoC Memoria DDR4-2666 soldado de 4GB Almacenamiento 1TB HDD 5400rpm 2.5 Monitor 15.6 "HD (1366x768) TN 220nits antideslumbrante',
     
    },
    {
      name: 'Gabinet Gamer Pc Gadnic Genesis 4 Coolers Rgb Atx',
      slug: '7',
      category: 'Gabinet',
      image: '/images/p7.png',
      price: 75,
      brand: 'Gadnic',
      countInStock: 20,
      description: ' Revestimiento negro SPCC (acero laminado) de 0,5 mmCompatible con placa base: ATX / M-ATX - USB 2.0 + HD AUDIO',
     
    },
    {
      name: 'Gamer Intel I5 9na Gen Ddr4 Hd 1tb Gtx 1650 4gb ',
      slug: '8',
      category: 'Computer gamer',
      image: '/images/p8.png',
      price: 530,
      brand: 'Intel',
      countInStock: 20,
      description: 'MICRO: INTEL i5 9400F 4.0GHZ 9NA GEN CON COOLER BOX. VIDEO: NVIDIA GEFORCE GTX 1050 Ti 4GB GDDR5 OC HDMI BOX..MOTHER: MSI/ASROCK H310M DISCO RIGIDO: 1000GB 7200RPM SATA3 TOSHIBA..MEMORIA RAM: 8GB 2400MHZ DDR4...GABINETE: ATX SENTEY X10 RGB POWER..FUENTE: SENTEY/LNZ LNZ550...',
      
    },
    {
      name: 'Gamer Ryzen 7 16gb Amd Rx550 + Ssd 256gb',
      slug: '9',
      category: 'Computer gamer',
      image: '/images/p9.png',
      isFeatured: true,
      featuredImage: '/images/banner4.png',
      price: 475,
      brand: 'Raysen',
      countInStock: 20,
      description: 'Marca: AMD Modelo: AMD 4700S -Procesador: AMD 4700S (8 núcleos, 16 hilos, 3.2 GHz, 7nm)-Memoria: 16 GB GDDR6 (cumple función de RAM/VRAM No expandible)-Ranuras PCIe: 1 ranura PCIe® x16, compatible con (señal x4 Gen 2)A ',
      
    },
    {
      name: 'Motherboard Msi Mpg Z390 Gaming Plus',
      slug: '10',
      category: 'Motherboard',
      image: '/images/p12.png',
      price: 175,
      brand: 'MSI',
      countInStock: 20,
      description: ' MPG Z390 GAMING PLUS disipador de calor extendido, Core boost, Twin Turbo M.2, Game Boost, Turbo USB y conector Intel CNVi y la última aplicación Dragon Center de MSI',
     
    },
    {
      name: ' AMD Ryzen 5 5600G',
      slug: '11',
      category: 'Computer gamer',
      image: '/images/p13.png',
      price: 550,
      brand: 'AMD',
      countInStock: 20,
      description: 'Gabinete Gamer Pc Atx Gadnic Apocalipsis Procesador AMD Ryzen 5 5600G c/ video Motherboard Gigabyte A520M-S2H Memoria para PC Crucial 8GB 2666 MHz DDR4 Disco Estado Solido Gigabyte 480GB Fuente Corsair 600w 80 Plus White Teclado Gadnic Retroiluminado Gaming 7 Mouse Gaming Gadnic M3 SHOOT',
    },
    {
      name: ' Keyboard Gamer Hyperx Alloy Elite 2 Rgb Teclas Multimedia',
      slug: '12',
      category: 'Keyboard/Mouse',
      image: '/images/p15.png',
      price: 550,
      brand: 'Hyperx',
      countInStock: 20,
      description: 'Tipo de tecla : HyperX Red   Retroiluminación : LED RGB  Factor de forma : Tamaño completo   Teclas multimedia : Específicas   Compatibilidad con NGENUITY    Perfiles de iluminación preajustados : 3   Conector USB 2.0 : Incluido en el Teclado',
    },
    {
      name: ' GTRACING Gaming Chair Racing Office Computer',
      slug: '13',
      category: 'Gamer accesories',
      image: '/images/p19.png',
      price: 550,
      brand: 'G.tracing',
      countInStock: 20,
      description: 'Ergonomic Design: Strong metal frame designed to help promote a comfortable seated position, keeping you comfy after long hours of game or work. Thick padded back & seat take this chair to the next level of comfort.',
    },
    {
      name: ' GTRACING Gaming Chair Racing Office',
      slug: '14',
      category: 'Gamer accesories',
      image: '/images/p20.png',
      price: 110,
      brand: 'G-tracing',
      countInStock: 20,
      description: 'Ergonomic Design: Strong metal frame designed to help promote a comfortable seated position, keeping you comfy after long hours of game or work. Thick padded back & seat take this chair to the next level of comfort.',
    },
    {
      name: ' Keyboard Gamer Hyperx Alloy + mouse Elite 2 Rgb Teclas Multimedia',
      slug: '15',
      category: 'Keyboard/Mouse',
      image: '/images/p16.png',
      price: 110,
      brand: 'Hyperx',
      countInStock: 20,
      description: 'Tipo de tecla : HyperX Red   Retroiluminación : LED RGB  Factor de forma : Tamaño completo   Teclas multimedia : Específicas   Compatibilidad con NGENUITY    Perfiles de iluminación preajustados : 3   Conector USB 2.0 : Incluido en el Teclado',
    },

  ],
};
export default data;
