import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import profile from '/public/black.png'
import NextLink from 'next/link';
import { Link, ListItemText,} from '@material-ui/core';
import db from '../utils/db';
import Product from '../models/Product';
import axios from 'axios';
import { useRouter } from 'next/router';
import { useContext,useEffect, useState} from 'react';
import { Store } from '../utils/Store';
import ProductItem from '../components/ProductItem';
import Carousel from 'react-material-ui-carousel';
import Typewriter from 'typewriter-effect';
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Modal from '../components/modal'

export default function Home(props) {

    const router = useRouter();
    const { state, dispatch } = useContext(Store);

    const { topRatedProducts, featuredProducts, allProducts } = props;
    const [modalOpen, setModalOpen] = useState(false);
    const [modalOpen2, setModalOpen2] = useState(false);
    const [modalOpen3, setModalOpen3] = useState(false);
    
  const addToCartHandler = async (product) => {
    const existItem = state.cart.cartItems.find((x) => x._id === product._id);
    const quantity = existItem ? existItem.quantity + 1 : 1;
    
    const { data } = await axios.get(`/api/products/${product._id}`);
  
    if (data.countInStock < quantity) {
      window.alert('Sorry. Product is out of stock');
      return;
    }
    dispatch({ type: 'CART_ADD_ITEM', payload: { ...product, quantity } });
        router.push('/cart');
  };
  const [categories, setCategories] = useState([]);
  const fetchCategories = async () => {
    try {
      const { data } = await axios.get(`/api/products/categories`);
      setCategories(data);
    } catch (err) {
      console.log(err)
    }
  };
  useEffect(() => {
    fetchCategories();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const settings = {
      centerMode: false,
      dots: false,
      infinite: false,
      speed: 500,
      slidesToShow: 5,
      initialSlide: 0,
  
    };
    // search
    const [query, setQuery] = useState('');
    const queryChangeHandler = (e) => {
    setQuery(e.target.value);
  };
    const submitHandler = (e) => {
    e.preventDefault();
    router.push(`/search?query=${query}`);
  };
  //button-show/hide
    const backHome=(e)=>{
    e.preventDefault();
    window.scroll(0, 0); 
  };

  return (
    <div className="container">
  
          <Script src="https://kit.fontawesome.com/a076d05399.js"></Script>
  
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
               
      </Head>

    
    <nav className="navbar" >
            <div className="max-width">
        {/* sidebar */}
        <div className="sidebar">
      <input type="checkbox" id="btn" hidden/>
      <label htmlFor="btn" className="menu-btn">
        <i className="fas fa-bars"></i>
        <i className="fas fa-times"></i>
        </label>
        <div id="sidebar">
        <div className="title">Side Menu</div>
        <ul className="list-items">
          <li><a href="#"><i className="fas fa-home"></i>Home</a></li>
          <li><a href="#"><i className="fas fa-sliders-h"></i>Clients</a></li>
          <li><a href="#"><i className="fas fa-address-book"></i>Services</a></li>
          <li><a href="#"><i className="fas fa-cog"></i>Settings</a></li>
          <li><a href="#"><i className="fas fa-stream"></i>Features</a></li>
          <li><a href="#"><i className="fas fa-user"></i>About us</a></li>
          <li><a href="#"><i className="fas fa-globe-asia"></i>Languages</a></li>
          <li><a href="#"><i className="fas fa-envelope"></i>Contact us</a></li>
          <div className="icons">
            <a href="#"><i className="fab fa-facebook-f"></i></a>
            <a href="#"><i className="fab fa-twitter"></i></a>
            <a href="#"><i className="fab fa-github"></i></a>
            <a href="#"><i className="fab fa-youtube"></i></a>
          </div>
        </ul>
      </div>
      </div>
        {/* sidebar end */}
    
            <div className="logo"><a href="#">Planet <i className="fas fa-globe-americas"></i><span> Gamer</span><i className="fab fa-xing"></i></a></div>
            <ul className="menu">
         
                <li><a href="#top" className="menu-btn">Top products </a></li>
                <li><a href="#sales" className="menu-btn">Sales</a></li>
                <li><a href="#services" className="menu-btn">Services</a></li>
                <li><a href="#contact" className="menu-btn">Contact</a></li>
                
            </ul>
          
        </div>
         <form className="search-box" onSubmit={submitHandler}>
                  <input type="text" placeholder="Type to search.." onChange={queryChangeHandler} />
             <button className="search-icon" type="submit">
                <i className="fas fa-search"   ></i>
             </button>
         </form>
         <ul className="menu2">
                    <li> <i className="fas fa-user"></i></li>
                   <li><NextLink href="/login" className="menu-btn"> Login</NextLink></li>
                  <li><NextLink href="/register" className="menu-btn">Register</NextLink></li>
          </ul>
    </nav>
    
    
    <section className="home" id="home">
             <div className="max-width">
                <div className="home-content">
                <Carousel className="images" animation="fade" interval="6000" indicators="false" >
        {featuredProducts.map((product) => (
          <NextLink
            key={product._id}
            href={`/product/${product.slug}`}
            passHref
          >
            <Link>
              <Image
                src={product.featuredImage}
                alt={product.name}
                height={500}
                width={600}
              ></Image>
            </Link>
          </NextLink>
        ))}
      </Carousel>
            <div className="translate">
                <div className="text-1">Welcome , GamerX..this is the e.commerce site for...</div>
     <Typewriter
            options={{
            strings: [' Gamers', 'Casters',' Developers',' Home office'],
            autoStart: true,
            loop: true,
                    }}
            onInit={(typewriter) => {
            typewriter.typeString()
            .callFunction(() => {
            console.log('String typed out!');
                                    })
                .pauseFor(5000)
                .deleteAll()
                .callFunction(() => {
                console.log('All strings were deleted');
                                    })
                .start();
                                    }}
      />
                </div>
             </div>
        </div>
        
      </section>
       {/*Categories*/}
       <section className="slider-categories">
                <header className="title-categories">Shopping by categories</header>   
                <div className="cardcontainer-categories">
                        <Slider {...settings}  >                      
                {categories.map((category) => (
                  <NextLink
                    key={category}
                    href={`/search?category=${category}`}
                    passHref
                  >
                    <ListItemText  className="categorieslist" primary={category}></ListItemText>
                                      
                  </NextLink>
                           ))}
                         </Slider>
                    </div>
            
       {/*end categories  */}  
       <br/>
       <br/>
       <br/>
       <div className="cardcontainer">
       <header className="title-categories">New products in stock</header>   
                       <Slider {...settings}  >
                          {allProducts.map((product) => {
                                return (
                                  <div className="cardcontainerinner" key={product.name}>
                                          <ProductItem product={product}
                                            addToCartHandler={addToCartHandler}
                                         />
                                    </div>
                                  );
                             })}
                        </Slider>
                    </div>
              <br/>
              <div className="top" id="top">
              <h2 className="title">Top rated </h2>
                    <div className="gallery"  >
                 {topRatedProducts.map((product) => (
          <div className="gallery-products "  key={product.name} >
            <ProductItem   product={product} addToCartHandler={addToCartHandler} />
         </div>
        ))}
      </div>
      </div>
                  {/* black friday */}
       <div className="sales" id="sales">
        <div className="max-width">
            <h2 className="title">Sales</h2>
                  <div className="card">
                    <div className="box">
                        <Image src={profile} alt="" width={800} height={500}/>
                   </div>          
                         <div className="button-area">
                            <button type="submit">More</button>
                         </div>
                </div>
            </div>
       </div>
                  <br/>
      <div className="services" id="services">
        <div className="max-width">
            <h2 className="title">Services</h2>
            <div className="serv-content">
                <div className="card">
                    <div className="box">
                    <i className="fas fa-credit-card"onClick={() => { setModalOpen2(true); }}></i>
                    {modalOpen2 && <Modal setOpenModal={setModalOpen2} >
                          <h3>Payments methods</h3>
                          <i className="fab fa-cc-paypal"></i>
                          <i className="fab fa-cc-stripe"></i>
                          <i className="fab fa-cc-visa"></i>
                          <i className="fab fa-cc-mastercard"></i>
                          <i className="fab fa-cc-amex"></i>

                          </Modal>}
                        <div className="text">Payments </div>
                        <p>Pay with confidence.quick and easy </p>
                    </div>
                </div>
                <div className="card" >
             
                    <div className="box">
                    <i className="fas fa-shipping-fast" onClick={() => { setModalOpen(true); }}></i>
                        {modalOpen && <Modal setOpenModal={setModalOpen} >
                        <h3>Shipping methods</h3>
                          <i className="fab fa-fedex"></i><p> $ 7.99 </p>
                          <i className="fab fa-ups"></i><p> $ 7.99 </p>
                          <i className="fab fa-dhl"></i><p> $ 7.99 </p>

                          </Modal>}
                        <div className="text">Shipping</div>
                        <p>Customized tax and shipping ..keep track of your shipping any time.</p>
                    </div>
                </div>
                <div className="card">
                    <div className="box">
                    <i className="fas fa-shield-alt" onClick={() => { setModalOpen3(true); }}></i>
                    {modalOpen3 && <Modal setOpenModal={setModalOpen3} >
                          <h3>Security</h3>
                          <p>security standards designed to ensure that ALL companies that accept,
                             process, store or transmit credit card information maintain a secure environment.</p>

                          </Modal>}
                        <div className="text">Security</div>
                        <p>Compliant with Payment Card Industry Data Security Standard </p>
                    </div>
                </div>
               </div>
            </div>
            <div className="scroll-up-btn" onClick={backHome}>
                <i className="fas fa-angle-up" ></i>
             </div>
          </div>
    <br/>    <br/>    <br/>
    </section>
  
    <section className="contact" id="contact">
        <div className="max-width">
                <div className="contact-content">
                <div className="column left">
                    <div className="text">Get in Touch</div>
                    <p>Please do not hesistate to contact us for technical support or any questions </p>
                    <div className="icons">
                        <div className="row">
                            <i className="fas fa-user"></i>
                            <div className="info">
                                <div className="head">Name</div>
                                <div className="sub-title">Guillermo Agnol</div>
                            </div>
                        </div>
                        <div className="row">
                            <i className="fas fa-map-marker-alt"></i>
                            <div className="info">
                                <div className="head">Address</div>
                                <div className="sub-title">C.A.B.A.- Argentina</div>
                            </div>
                        </div>
                        <div className="row">
                        <i className="fab fa-whatsapp"></i>
                            <div className="info">
                                <div className="head">whatsapp</div>
                                <div className="sub-title">(5411) 3046-9916</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="column right">
                    <div className="text">Message me</div>
                    <form action="#">
                        <div className="fields">
                            <div className="field name">
                                <input type="text" placeholder="Name" required/>
                            </div>
                            <div className="field email">
                                <input type="email" placeholder="Email" required/>
                            </div>
                        </div>
                        <div className="field">
                            <input type="text" placeholder="Subject" required/>
                        </div>
                        <div className="field textarea">
                            <textarea cols="30" rows="10" placeholder="Message.." required></textarea>
                        </div>
                        <div className="button-area">
                            <button type="submit">Send message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div className="scroll-up-btn" onClick={backHome}>
                <i className="fas fa-angle-up" ></i>
             </div>
    </section>
    <br/>

    <footer>  
        <span>Created By Planet•GamerX | <span className="far fa-copyright"></span> all rigths reserved &reg;{new Date().getFullYear()}</span>
    </footer>

</div>  

  )
}

export async function getServerSideProps() {
    await db.connect();
    const featuredProductsDocs = await Product.find(
      { isFeatured: true },
      '-reviews'
    )
      .lean()
      .limit(10);
   
      const allProductsDocs = await Product.find({}, '-reviews')
      .lean()
      .sort({
        rating: -1,
         
      })
      .limit(100);

    const topRatedProductsDocs = await Product.find({}, '-reviews')
      .lean()
      .sort({
        rating: -1,
         
      })
      .limit(14);
    await db.disconnect();
    return {
      props: {
        featuredProducts: featuredProductsDocs.map(db.convertDocToObj),
        allProducts:    allProductsDocs.map(db.convertDocToObj),
        topRatedProducts: topRatedProductsDocs.map(db.convertDocToObj),     
        
      },
    };
  }